//User Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Post Image

export const GETURI_SUCCESS = "GETURI_SUCCESS";
export const GETURI_FAIL = "GETURI_FAIL";

//Posts
export const GETPOSTS_ANOTHERPAGE = "GETPOSTS_ANOTHERPAGE";
export const GETPOSTS_REQUEST = "GETPOSTS_REQUEST";
export const GETPOSTS_SUCCESS = "GETPOSTS_SUCCESS";
export const GETPOSTS_FAIL = "GETPOSTS_FAIL";
export const DELETEPOST_SUCCESS = "DELETEPOST_SUCCESS";
export const DELETEPOST_FAIL = "DELETEPOST_FAIL";

//Comment
// export const GETURI_SUCCESS = "GETURI_SUCCESS";
// export const GETURI_FAIL = "GETURI_FAIL";
export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_REQUEST";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";
