/*
  This file store all dispatch types . 
  Dispatch types of each feature will be grouped together.
*/

//User Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const USERLOADED_FAIL = "USERLOADED_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const RESET_FORM = "RESET_FORM";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Post Image
export const GETURI_SUCCESS = "GETURI_SUCCESS";
export const GETURI_FAIL = "GETURI_FAIL";

//Posts
export const EDITPOST_SUCCESS = "EDITPOST_SUCCESS";
export const EDITPOST_FAIL = "EDITPOST_FAIL";
export const CREATEPOST_SUCCESS = "CREATEPOST_SUCCESS";
export const CREATEPOST_FAIL = "CREATEPOST_FAIL";
export const CLEARPOSTS_SUCCESS = "CLEARPOSTS_SUCCESS";
export const GETPOSTS_ANOTHERPAGE = "GETPOSTS_ANOTHERPAGE";
export const GETPOSTS_REQUEST = "GETPOSTS_REQUEST";
export const GETPOSTS_SUCCESS = "GETPOSTS_SUCCESS";
export const GETPOSTS_FAIL = "GETPOSTS_FAIL";
export const DELETEPOST_SUCCESS = "DELETEPOST_SUCCESS";
export const DELETEPOST_FAIL = "DELETEPOST_FAIL";

//Comment
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAIL = "COMMENT_FAIL";
export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";
export const CLOSE_COMMENT = "CLOSE_COMMENT";
export const CLEAR_COMMENT = "CLEAR_COMMENT";
export const POSTCOMMENT_SUCCESS = "POSTCOMMENT_SUCCESS";
export const POSTCOMMENT_FAIL = "POSTCOMMENT_FAIL";
export const EDITCOMMENT_FAIL = "EDITCOMMENT_FAIL";
export const DELETECOMMENT_SUCCESS = "DELETECOMMENT_SUCCESS";
export const EDITCOMMENT_SUCCESS = "EDITCOMMENT_SUCCESS";
export const CREATECOMMENT_SUCCESS = "CREATECOMMENT_SUCCESS";

//Emojis
export const POSTEMOJI_SUCCESS = "POSTEMOJI_SUCCESS";
export const POSTEMOJI_FAIL = "POSTEMOJI_FAIL";
export const DELETEEMOJI_SUCCESS = "DELETEMOJI_SUCCESS";
export const DELETEEMOJI_FAIL = "DELETEEMOJI_FAIL";

//Leaderboard
export const GET_RANK_REQUEST = "GET_RANK_REQUEST";
export const GET_RANK_SUCCESS = "GET_RANK_SUCCESS";
export const GET_RANK_FAIL = "GET_RANK_FAIL";
